{* Override this file (via skinning) to add customer staff links for ADMINs *}

<li class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Staff Links<b class="caret"></b></a>
                                
    <ul class="dropdown-menu">
        <li> <a href="https://staff.lonap.net/rt/">RT Ticketer</a> </li>
        <li> <a href="https://staff.lonap.net/">Staff Wiki</a> </li>
        <li> <a href="https://mon.lonap.net/nagios3/">Nagios Monitoring</a> </li>
        <li> <a href="https://github.com/inex/IXP-Manager">IXP Manager @ GitHub</a> </li>
    </ul>
</li>

