{* Override this file (via skinning) to add customer staff links for ADMINs *}

<li class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Staff Links<b class="caret"></b></a>
                                
    <ul class="dropdown-menu">
        <li> <a href="https://staff.lonap.net/rt/">RT Ticketer</a> </li>
        <li> <a href="https://staff.lonap.net/">Wiki</a> </li>
        <li> <a href="https://mail.lonap.net/cgi-bin/mailman/admin/members">Members List Management</a></li>
    </ul>
</li>

