<div class="row-fluid">
    <div class="span6">
    
        <h3>LONAP News</h3>
        <br />

        <ul>
            <li>
                <strong>New bidirectional fibre port service -</strong>
                We are now able to offer 2 x 1G or 2 x 10G LAG using bidirectional optics (1000Base-BX10-U or equivalent 10G) Two ports can be connected using only one pair of single mode fibre, saving additional crossconnect cabling requirements, and offering an quick upgrade path for existing single mode fibre connections. Please <a href="mailto:support@lonap.net">contact us</a> for advice on which optics/wavelengths to use.
            </li>
<!--
            <li>
                <strong>New Peering Manager now available</strong>. 
                <a href="{genUrl controller="peering-manager"}">Check it out here</a>.
            </li>
-->
            <li>
                <strong>Upgrade to IXP Manager 3.6.6</strong>
                We are upgraded to IXP Manager 3.6.6. Graphs for errors are now available in your port and aggregate traffic stats, along with a few other fixes and improvements.
                <a href="https://portal.lonap.net/statistics/member/">Check them out here</a>. (Although we hope that the error graphs will be pretty boring most of the time!)
            </li>
            <li>
                You can now manage your mailing list subscriptions via
                your <a href="{genUrl controller="profile"}">profile page</a>.
            </li>
<!--
            <li> Redesigned <a href="{genUrl controller="dashboard" action="statistics"}">statistics pages</a> making them clearer and more intuitive. </li>
            <li>
                Added weather maps for peering <a href="{genUrl controller="dashboard" action="weathermap" id=1}">LAN 1</a>
                and <a href="{genUrl controller="dashboard" action="weathermap" id=2}">LAN 2</a> showing inter-PoP
                trunk untilisation and other information based on feedback from members.
            </li>
-->
            
        </ul>
        
    </div>
    
    <div class="span6">
        &nbsp;
    </div>
</div>

