{if isset( $options.mailinglist.enabled ) and $options.mailinglist.enabled}
    <h3>Your Mailing List Subscriptions</h3>
    <p>
        <br />
        {$options.identity.orgname} operates the following mailing lists to help us interact with our
        members and for our members to interact with each other.

	<ul>
	   <li><b>members</b>: Members list (members@lonap.net) for maintenance and announcements from LONAP and peers, occasional discussion. (light traffic)</li>
	   <li><b>members-post</b>: Subscribe to members-post if you want to be able to post to the members list from {$user->getEmail()}, but <i>do not</i> want to receive copies of list posts. (e.g. you are already subscribed via another address or alias.)</li>
	</ul>

    </p>
    <p>
        There are also links to the list archives - for which your username is
        {$user->getEmail()} and your password is the same as your IXP Manager password.
    </p>
    <p>
        Here are your subscriptions for <strong>{$user->getEmail()}</strong>:
    </p>
    <br />
    <form action="{genUrl controller="profile" action="update-mailing-lists"}" method="post" class="form">
    <fieldset>

        {foreach $options.mailinglists as $name => $ml}

        {if $user->getCustomer()->getType() neq CUSTOMER::TYPE_ASSOCIATE or ( isset( $ml.associates ) and $ml.associates )}

                <div class="control-group">
                    <label class="checkbox">
                        <input type="checkbox" name="ml_{$name}" value="1" {if $mlsubs.$name}checked="checked"{/if}>
                            <strong>{$ml.name}</strong> - {$ml.desc}
                            ({if $ml.email}{mailto address=$ml.email} - {/if}<a href="{$ml.archive}">archives</a>)
                    </label>
                </div>
            {/if}

        {/foreach}
    
        <div class="form-actions">
            <input type="submit" class="btn btn-primary" value="Update My Subscriptions" id="submit" name="submit">
        </div>
    
    </fieldset>
    </form>
{/if}
