{tmplinclude file="header.phtml"}

{if $user->getPrivs() eq 3}
    <ul class="breadcrumb">
        <li>
            <a href="{genUrl}">Home</a> <span class="divider">/</span>
        </li>
        <li>
            Documentation <span class="divider">/</span>
        </li>
        <li class="active">
            Miscellaneous Benefits
        </li>
    </ul>
    
    <div>
{else}
    <div class="page-content">
        <div class="page-header">
            <h1>Miscellaneous Benefits</h1>
        </div>
{/if}

<h3>TBD</h3>


<p>
This page needs updating
</p>

<!--
<table border="0">
<tr>
    <td width="50"></td>
    <td align="right"><strong>Server name:</strong></td>
    <td width="20"></td>
    <td align="left"><code>irc.xxx.xxxx</code>, port 6697, SSL enabled</td>
</tr>
<tr>
    <td></td>
    <td align="right"><strong>Channel:</strong></td>
    <td></td>
    <td align="left"><code>#xxxx-ops</code></td>
</tr>
<tr>
    <td></td>
    <td align="right"><strong>Password:</strong></td>
    <td></td>
    <td align="left"><code>xxxxxxx</code></td>
</tr>
</table>
-->

</div>

{tmplinclude file="footer.phtml"}
