{tmplinclude file="header.phtml"}

{if isset( $user ) and $user->getPrivs() eq 3}
    <ul class="breadcrumb">
        <li>
            <a href="{genUrl}">Home</a> <span class="divider">/</span>
        </li>
        <li>
            Documentation <span class="divider">/</span>
        </li>
        <li class="active">
            Technical Support and Contact Information
        </li>
    </ul>
{else}
    <div class="page-content">
        <div class="page-header">
            <h1>Technical Support</h1>
        </div>
{/if}

<div class="alert alert-info">
    <h4 align="center">
        Support: {mailto address="support@lonap.net" encode="javascript"}
        &nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;
        Accounts: {mailto address="accounts@lonap.net" encode="javascript"}
        &nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;
        Sales / Marketing: {mailto address="sales@lonap.net" encode="javascript"}
    </h4>
</div>

<h3>Contacting LONAP Support</h3>

<p>
Regular technical support at LONAP is provided on an office hours basis from 09:00 to 17:30 Local time, Monday - Friday. The normal 
communications channel for technical support is email to {mailto address="support@lonap.net" encode="javascript"}. 
LONAP staff are also available by telephone on +44 20 3137 8330.<br /><br />
</p>

<h3>Out of hours support</h3>

<p>
An 24-hour support pager is available for emergency calls which fall outside normal 
office hours. This support facility is intended for emergencies only, including:
</p>

<ul>
    <li> a member port is down </li>
    <li> there is a traffic anomaly </li>
    <li> there is a major fault in the core LONAP network and this problem is severely affecting member traffic </li>
    <li> This may be different for each member, but in general we would consider accidental tripping of port security, ports being down unexpectedly or errors on ports as likely candidates to be classed as an emergency if it is affecting customer traffic sufficiently.</li> 
</ul>

Send a message out of hours here: <a href="http://emergency.lonap.net/">http://emergency.lonap.net/</a>

<br /><br />

{if not isset( $user ) or $user->getPrivs() neq 3}
    </div>
{/if}

{tmplinclude file="footer.phtml"}
